// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb8FSrVpVVHIwYqtPAs-xE0YZFFCwk_Rk',
    appId: '1:928669499727:web:cf51caa38269fc874e053a',
    messagingSenderId: '928669499727',
    projectId: 'fyp-project-95056',
    authDomain: 'fyp-project-95056.firebaseapp.com',
    storageBucket: 'fyp-project-95056.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADQmqy13TASFE8A6e520kXBELKcHU1b-E',
    appId: '1:928669499727:android:7a7d6fd79e6e485c4e053a',
    messagingSenderId: '928669499727',
    projectId: 'fyp-project-95056',
    storageBucket: 'fyp-project-95056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMQAoleg3L670wKqYvHme55nMwyMw4a4I',
    appId: '1:928669499727:ios:2bd18664416bf7074e053a',
    messagingSenderId: '928669499727',
    projectId: 'fyp-project-95056',
    storageBucket: 'fyp-project-95056.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMQAoleg3L670wKqYvHme55nMwyMw4a4I',
    appId: '1:928669499727:ios:2bd18664416bf7074e053a',
    messagingSenderId: '928669499727',
    projectId: 'fyp-project-95056',
    storageBucket: 'fyp-project-95056.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb8FSrVpVVHIwYqtPAs-xE0YZFFCwk_Rk',
    appId: '1:928669499727:web:56cf68f507c7aa764e053a',
    messagingSenderId: '928669499727',
    projectId: 'fyp-project-95056',
    authDomain: 'fyp-project-95056.firebaseapp.com',
    storageBucket: 'fyp-project-95056.firebasestorage.app',
  );

}